### ISSUE TITLE
Add CI/CD tools for NPM module dependency management.

### ISSUE THREAD

**Issue by jthomas** [apache/openwhisk-client-js#179]
e.g Greenkeeper & Synk.

**Comment by jthomas** [comment]
Opened an INFRA ticket to do this: https://issues.apache.org/jira/browse/INFRA-18705

**Comment by jthomas** [comment]
INFRA said no. Waiting for clarification on this rule after emailing the mailing list...

**Comment by dgrove-oss** [comment]
Policy changed; we have dependabot enabled for this repo.  Closing as done
