### ISSUE TITLE
Please publish a new minor version 3.22.0

### ISSUE THREAD

**Issue by purplecabbage** [apache/openwhisk-client-js#260]
3.21.7 is still latest, but is is using  needle: ^2.4.0
I sent a pr that was merged 2 months ago to bump needle to ^3.2.0

Users are seeing repeated TLS errors "Remote End Closed Socket Abruptly"

**Comment by dgrove-oss** [comment]
Taking a look to see if I can get the CI for this repo ported from TravisCI to GitHub Actions.  We should also do some dependency updates before making a release and I'd like to have CI working to validate them.

**Comment by dgrove-oss** [comment]
Got CI working in #261  -- once that is merged, we can update dependencies and then working on release notes, etc.

**Comment by dgrove-oss** [comment]
vote in progress; hope to release by the end of this week.

**Comment by dgrove-oss** [comment]
3.21.8 officially released and published to npm.
